answer_crewai_questions_task:
  agent: crewai_expert_agent
  description: >
    Respond to user questions about the CrewAI framework.

    Current message: {current_message}
    Conversation history: {conversation_history}
  expected_output: >
    Response should be less than 1000 characters unless there is a code example.

    Responses should be informative and helpful, addressing the user's questions about CrewAI.
    If required:
    - Provide links to relevant documentation
    - Offer practical examples