answer_crewai_questions_task:
  agent: crewai_expert_agent
  description: >
    Respond to user questions about the CrewAI framework.

    Current message: {current_message}
    Conversation history: {conversation_history}
  expected_output: >
    If required:
    - Provide links to relevant documentation
    - Offer practical examples